name: Push latest Docker image

on:
  push:
    # Trigger if latest_candidate updates. This is automatically done by another
    # workflow whenever tests pass on main - but events don't chain without using
    # personal access tokens so we just use a cron job.
    branches: [ latest_candidate ]
  schedule:
    # Run at 5:41 UTC daily
    - cron:  '41 5 * * *'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push latest Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: latest_candidate
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tags: latest
      - name: Update latest branch
        uses: ad-m/github-push-action@8407731efefc0d8f72af254c74276b7a90be36e1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: latest
          force: true
